# Generated by Django 2.2.1 on 2019-05-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections_beta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stuid',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vid',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
