# Generated by Django 2.2.1 on 2019-05-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections_beta', '0002_auto_20190518_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canid', models.IntegerField()),
                ('can_name', models.CharField(max_length=200)),
                ('can_votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stu_name', models.CharField(max_length=200)),
                ('vote1', models.IntegerField()),
                ('vote2', models.IntegerField()),
                ('vote3', models.IntegerField()),
                ('vote4', models.IntegerField()),
                ('vote5', models.IntegerField()),
                ('vote6', models.IntegerField()),
            ],
        ),
    ]
