# Generated by Django 2.2.1 on 2019-05-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections_beta', '0005_auto_20190518_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_vote_status',
            field=models.BooleanField(default=False),
        ),
    ]
