# Generated by Django 2.2.1 on 2019-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections_beta', '0006_student_stu_vote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='can_votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
