# Generated by Django 2.2.1 on 2019-05-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections_beta', '0007_auto_20190519_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='can_votes',
            field=models.IntegerField(default=0),
        ),
    ]
