# Generated by Django 2.2.1 on 2019-05-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections_beta', '0008_auto_20190519_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='canid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stuid',
            field=models.IntegerField(unique=True),
        ),
    ]
